#!/bin/bash

{
echo "selinux_st:$(sestatus | awk '{print$3}')"
echo "firewall_st1:$(systemctl status firewalld | grep "Active:" | awk '{print$2}')"
echo "firewall_st2:$(systemctl is-enabled firewalld)"
echo "ntp_st1:$(systemctl status ntpd | grep "Active:" | awk '{print$2}')"
echo "ntp_st2:$(systemctl is-enabled ntpd)"
echo "rclocal_st1:$(systemctl status rc-local | grep "Active:" | awk '{print$2}')"
echo "rclocal_st2:$(systemctl is-enabled rc-local)"
echo "kdump_st1:$(systemctl status kdump | grep "Active:" | awk '{print$2}')"
echo "kdump_st2:$(systemctl is-enabled kdump)"
echo "hostname:$(hostname)"
echo "os_ver:$(cat /etc/redhat-release)"
echo "kernel_ver:$(uname -r)"
echo "mtu:$(netstat -i | grep ens | awk '{print$2}' | head -1)"
echo "hosts:"
echo "$(cat /etc/hosts)"
echo ":hosts"
echo "df:"
echo "$(df -Th)"
echo ":df"
echo "fstab:"
echo "$(cat /etc/fstab)"
echo ":fstab"
echo "resolve:"
echo "$(cat /etc/resolv.conf)"
echo ":resolve"
echo "sysctl:"
echo "$(cat /etc/sysctl.conf)"
echo ":sysctl"
echo "grubby:"
echo "$(cat /etc/grub2.cfg)"
echo ":grubby"
echo "ulimit:"
echo "$(cat /etc/security/limits.d/20-nproc.conf)"
echo ":ulimit"
echo "blockdev:"
echo "$(blockdev --getra /dev/sd*)"
echo ":blockdev"
echo "logind:"
echo "$(cat /etc/systemd/logind.conf)"
echo ":logind"
echo "sshd:"
echo "$(cat /etc/ssh/sshd_config)"
echo ":sshd"
echo "yum:"
echo "$(ls /etc/yum.repos.d/)"
echo ":yum"
} > /tmp/check_status_$(hostname)
